;
;==================================================================================================
; GLOBAL ERROR MANAGEMENT
;==================================================================================================
;
; ERROR NUMBERS ARE DEFINED IN HBIOS.INC
;
;
;-----------------------------------------------------------------------
; RETURN A POINTER IN DE TO AN ERROR STRING.  ERROR CODE IN A
;-----------------------------------------------------------------------
;
ERR_GETSTR:
	PUSH	AF
	PUSH	HL
	NEG				; CONVERT TO POSITIVE NUMBER
	CP	ERR_CNT			; COMPARE TO MAX ERR NUM
	JR	C,ERR_GETSTR1		; CONTINUE IF IN RANGE
	LD	A,ERR_UNDEF		; ... ELSE MAKE IT UNDEFINED
ERR_GETSTR1:
	ADD	A,A			; MAKE IT A WORD OFFSET
	LD	HL,ERR_STR_TABLE	; POINT TO ERROR STRINGS TABLE
	CALL	ADDHLA			; BUMP TO SPECIFIC ERROR STRING
	LD	E,(HL)			; DEREF INTO DE
	INC	HL
	LD	D,(HL)
	POP	HL
	POP	AF
	RET
;
;-----------------------------------------------------------------------
; PRINT ERROR CODE IN REG A TO CONSOLE
;-----------------------------------------------------------------------
;
ERR_PRT_SP:
	; VARIANT TO PREFIX ERROR STRING WITH A SPACE
	CALL	PC_SPACE
;
ERR_PRT:
	PUSH	DE
	CALL	ERR_GETSTR
	CALL	WRITESTR
	POP	DE
	RET
;
;-----------------------------------------------------------------------
; ERROR STRING TABLE
;-----------------------------------------------------------------------
;
; ENTRIES *MUST* BE IN THE SAME ORDER AS ERROR NUMBERS AND MUST HAVE
; EXACTLY ONE ENTRY PER ERROR CODE.
;
ERR_STR_TABLE:
	.DW	STR_ERR_NONE	
	.DW	STR_ERR_UNDEF	
	.DW	STR_ERR_NOTIMPL	
	.DW	STR_ERR_NOFUNC	
	.DW	STR_ERR_NOUNIT	
	.DW	STR_ERR_NOMEM	
	.DW	STR_ERR_RANGE	
	.DW	STR_ERR_NOMEDIA	
	.DW	STR_ERR_NOHW	
	.DW	STR_ERR_IO	
	.DW	STR_ERR_READONLY
	.DW	STR_ERR_TIMEOUT	
	.DW	STR_ERR_BADCFG	
	.DW	STR_ERR_INTERNAL
	.DW	STR_ERR_NOTRDY
;
ERR_STR_CNT	.EQU	(($ - ERR_STR_TABLE) / 2)
;
#IF (ERR_STR_CNT != ERR_CNT)
	.ECHO	"*** ERROR: ERROR STRING TABLE ENTRIES DO NOT MATCH ERROR COUNT!!!\n"
	!!!	; FORCE AN ASSEMBLY ERROR
#ENDIF
;
STR_ERR_NONE		.TEXT	"OK$"
STR_ERR_UNDEF		.TEXT	"UNDEFINED ERROR$"
STR_ERR_NOTIMPL		.TEXT	"NOT IMPLEMENTED$"
STR_ERR_NOFUNC		.TEXT	"INVALID FUNCTION$"
STR_ERR_NOUNIT		.TEXT	"INVALID UNIT$"
STR_ERR_NOMEM		.TEXT	"OUT OF MEMORY$"
STR_ERR_RANGE		.TEXT	"PARAMETER OUT OF RANGE$"
STR_ERR_NOMEDIA		.TEXT	"MEDIA NOT PRESENT$"
STR_ERR_NOHW		.TEXT	"HARDWARE NOT PRESENT$"
STR_ERR_IO		.TEXT	"I/O ERROR$"
STR_ERR_READONLY	.TEXT	"READ-ONLY$"
STR_ERR_TIMEOUT		.TEXT	"TIMEOUT$"
STR_ERR_BADCFG		.TEXT	"INVALID CONFIGIURATION$"
STR_ERR_INTERNAL	.TEXT	"INTERNAL ERROR$"
STR_ERR_NOTRDY		.TEXT	"DEVICE NOT READY$"
